# Site settings
title: Carl's portfolio
description: This is Carl's portfolio.
theme: jekyll-theme-time-machine

# Build settings
markdown: kramdown
permalink: /:title/

remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
